# Generated by Django 5.0 on 2023-12-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('درحال ثبت نام', 'Registeration'), ('جذب سرمایه', 'Fundraising'), ('درحال ساخت', 'Construction'), ('پایان کار', 'End')], default='درحال ثبت نام', max_length=20),
        ),
    ]
