# Generated by Django 5.0 on 2023-12-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contractor_name',
            field=models.CharField(max_length=50),
        ),
    ]
