# Generated by Django 5.0 on 2023-12-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='receipt_photo',
            field=models.ImageField(upload_to='uploads/receipt_photos/'),
        ),
    ]
