# Generated by Django 5.0 on 2023-12-26 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_project_contractor_name'),
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('project', 'profile')},
        ),
    ]
