# Generated by Django 5.0 on 2023-12-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_participation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location_x',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='location_y',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
