# Generated by Django 5.0 on 2023-12-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_participation_receipt_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='unit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
