# Generated by Django 5.0 on 2023-12-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_participation_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c4group',
            name='unit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
